apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-journal-server-deployment
  labels:
    app: phone-journal-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phone-journal-server
  template:
    metadata:
      labels:
        app: phone-journal-server
    spec:
      containers:
      - name: phone-journal-server
        image: ghcr.io/maxwellpeterson/phone-journal-server:main
        ports:
        - containerPort: 80
        env:
        - name: GIN_MODE
          value: release
        envFrom:
        - secretRef:
            name: phone-journal-server-secret
---
apiVersion: v1
kind: Service
metadata:
  name: phone-journal-server
spec:
  selector:
    app: phone-journal-server
  ports:
    - protocol: TCP
      port: 80